spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/brickstore-dev
    username: alex
    password: test123
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      resourceId: inventory-service
      clientId: brickstore-client-prototype
      userInfoEndpointUrl: http://localhost:8095/user/me

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 10
server:
  port: 8103

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

springdoc:
  swagger-ui:
    operations-sorter: method
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  show-actuator: true

#logging:
#  level:
#    root: INFO
#    org.springframework.web: INFO
#    org.springframework.web.HttpLogging: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.security.oauth2: DEBUG



